-- AlterTable
ALTER TABLE "gifts" ADD COLUMN     "boughtAt" TIMESTAMP(3),
ADD COLUMN     "byLink" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
